### ISSUE TITLE
Steam version cannot launch

### ISSUE THREAD

**Issue by Sol1vaN** [InsanityBringer/InjectD3#1]
Hi, incredible project. I hope this will have more updates soon.

btw, I've the Steam version and this cannot launch, this simply close and nothing happens.
So, trough the cmd this show an extrange error, look: CreateProcess("main.exe") failed; error code = 0x000002E4
![Sin título](https://user-images.githubusercontent.com/33560454/134842643-3b16b8cc-60bd-4c71-8f60-d483c8f17d0f.png)

The byte size is correct for the US 1.4 version, exactly 1,794,048 bytes
![2](https://user-images.githubusercontent.com/33560454/134842917-a1b84603-28f2-4eb1-97eb-4a0f84b88f35.png)

I don't know what happens.
Can you help me?

**Comment by InsanityBringer** [comment]
The specific error code indicates that the process requires elevation, do you have Descent 3 set to run as adminstrator? If so, you can either try running InjectD3 as an adminstrator, or you can disable running as adminstrator and set the configuration to use HKEY_CURRENT_USER, assuming you can still write to that directory.

**Comment by Sol1vaN** [comment]
Thanks! it work now!
