### ISSUE TITLE
Unlock descent 3 max texture resolution(over 256 px)

### ISSUE THREAD

**Issue by kryptnite** [InsanityBringer/InjectD3#10]
Hi,

It seems apparently that D3 don't support textures over 256x256 pixels.
Having tried this with a 512px texture lead to app crash.

D3 in order to receive a decent upscale pack need this limitation off.
With a max texture to be 8k(for sky texture). Preferably.Of course since D3 is 32 bit app i think using 1024px most of time.And 8k only for sky textures since they are very blurry. Again if possible.Set the max res you think it can be supported.

So far: 

I have seen this limitation on level textures.
I didn't try ship/robot textures.
I  have seen we don't have this limitation on weapon sprite.(tested only on 512px).

To implement Hires textures, do the following:

1---Hog2 workshop to see through game file.Export Any textures you want.

2---Use D3 image tool (importing/exporting) 

*Export the ogf texture to tga
*Resize tga to higher res
*Then tga to ogf using the tool
Put the new ogf in "Descent 3\custom\graphics" folder.

->grab the tools on "https://sectorgame.com/d3/downloads/?nav=browse&category=Development_Tools"

don't hesitate to call me for help.

thanks.

**Comment by InsanityBringer** [comment]
I'm intending to patch the texture upload code at some point (it's needed to implement the specular lighting properly), I can take a look into upping the limit when I work on that.

**Comment by InsanityBringer** [comment]
This is addressed in commit 0b8fffb and will be in the next update. Do note that there isn't much error checking here so it might still crash or you'll see weird artifacts such as textures changing into other ones if you exceed your GPU's assigned limits, or any other hard limits within the bitmap system. But I tested images up to 1024x1024, and it seems to [work fine](https://cdn.discordapp.com/attachments/588754776062427137/1055254867477811300/image.png)

**Comment by kryptnite** [comment]
ok, great.

Also i think it may me useful to 4GB patch the app(google it) .
Do you think you can implement this on the injector?
