### ISSUE TITLE
OpenAL Sound Code Doppler Effect

### ISSUE THREAD

**Issue by nghtsrfr** [InsanityBringer/InjectD3#6]
The doppler effect that is introduced with the OpenAL Sound Code set to True is quite noticeable on the trains in D3M4. Whereas they would usually be a low rumble, they instead have a very quick high to low transition in sound as they speed past. With multiple trains, it's actually quite hilarious, but problematic. I can provide a screen/audio recording if necessary!

**Comment by InsanityBringer** [comment]
I can try to tune the effect. One annoying thing is that the original game did support doppler shift if you had the right fancy sound cards, but I have no means to convert the values it provides to something that works with OpenAL's system. I need to find a good balance between actually being able to perceive the effect in normal gameplay but also not making things like the trains too weird (the Squid robot also seems weirdly affected)

**Comment by kaizerwolf** [comment]
It actually affects alarms fairly badly as well. Any relatively stationary sound source seems insanely affected by the doppler. Is there any way to separate the fixed audio (the removal of static and crackling) and the doppler effect? Not sure if it's possible to have the doppler be a boolean choice in the InjectD3 launcher, separate from the OpenAL Sound Code.

**Comment by InsanityBringer** [comment]
It wouldn't be hard to split out into an option, I thought I already had but that's only reverb effects. Though I'll probably tune the effect some first.

**Comment by InsanityBringer** [comment]
Added it, finally. It defaults to the current value of 0.6. Higher values will increase the pitch range as you move, whereas values below 0.6 will lower the range. At 0 the feature will effectively be disabled and sounds won't vary in pitch based on velocity.
